@HOST =http://localhost:8090
@HOSTL =http://localhost:8090
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGE5Nzg0NmE2ZTRjMTE5ZDFlN2RhMjUiLCJlbWFpbCI6ImFmbmFuQHVjb2RlLmFpIiwicGVybWlzc2lvbkxldmVsIjoiMSIsImxhc3ROYW1lIjoiQWhtZWQiLCJvcmdhbml6YXRpb24iOiI2NGE5NmNiNGU0YTE1ODdkOGY5NzhmZmYiLCJ3ZWJBY2Nlc3MiOjAsInJlZnJlc2hLZXkiOiJZcWYxY1RXNkF5U3dLSmZ0dEU2Y2lBPT0iLCJpYXQiOjE2OTUwOTQ1NDd9.aXDCu0XCEcWe2QZOrnB6RZ9MNIdTLjDDBqknmPgwyWA
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"afnan@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/accountbook HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"particular":"sitclf",
"receiptNo":"fugiat",
"amount":700,
"category":"Car",
"organizationId":"",
"memo":"Adipisicing occaecat do ea fugiat ad sit ullamco nisi."
}

###

GET {{HOST}}/accountbook? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOSTL}}/accountbook?category=Car&category_mode=in&page=0&limit=10 HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/accountbook/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/accountbook/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"particular":"sitclf",
"receiptNo":"fugiat",
"amount":"1",
"category":"minim",
"memo":"Adipisicing occaecat do ea fugiat ad sit ullamco nisi."
}
###
PATCH {{HOST}}/accountbook/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"particular":"sitclf",
"receiptNo":"fugiat",
"amount":"1",
"category":"minim",
"memo":"Adipisicing occaecat do ea fugiat ad sit ullamco nisi."
}
###
DELETE {{HOST}}/accountbook/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 

@HOST =https://app.ikra.my
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDk2Y2UxOWFhZGExMzI3OGE5ZGZlMjUiLCJlbWFpbCI6InRlc3RAdWNvZGUuYWkiLCJwZXJtaXNzaW9uTGV2ZWwiOiIwIiwibGFzdE5hbWUiOiJ1Q29kZSIsIm9yZ2FuaXphdGlvbiI6IiIsIndlYkFjY2VzcyI6MCwicmVmcmVzaEtleSI6IlRZVmZYVmNsVFZUbkJmRnBDQTQrZkE9PSIsImlhdCI6MTY4ODg3NjkzOX0.7jlADAhQhFDX30DYRO_Qumg-bk-fpfVIDY-b_wgx0bY
###
GET {{HOST}}/chart/all HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOSTL}}/accountbookfix
Authorization: Bearer {{AUTH}}


@AUTH2 =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGE5Nzg0NmE2ZTRjMTE5ZDFlN2RhMjUiLCJlbWFpbCI6ImFmbmFuQHVjb2RlLmFpIiwicGVybWlzc2lvbkxldmVsIjoiMSIsImxhc3ROYW1lIjoiQWhtZWQiLCJvcmdhbml6YXRpb24iOiI2NGE5NmNiNGU0YTE1ODdkOGY5NzhmZmYiLCJ3ZWJBY2Nlc3MiOjAsInJlZnJlc2hLZXkiOiJZcWYxY1RXNkF5U3dLSmZ0dEU2Y2lBPT0iLCJpYXQiOjE2OTUwOTQ1NDd9.aXDCu0XCEcWe2QZOrnB6RZ9MNIdTLjDDBqknmPgwyWA
###
POST http://localhost:8090/accountbook HTTP/1.1
Authorization: Bearer {{AUTH2}}
content-type: application/json

{
"particular":"sitclf",
"receiptNo":"fugiat",
"amount":455,
"category":"Car",
"organizationId":"",
"memo":"Adipisicing occaecat do ea fugiat ad sit ullamco nisi."
}

###

POST http://localhost:8090/auth HTTP/1.1
content-type: application/json

{
"email":"afnan@ucode.ai",
"password":"123456"
}